### ISSUE TITLE
"长度超限" Error when adding TOTP/HOTP key

### ISSUE THREAD

**Issue by lunzima** [canokeys/canokey-core#100]
Here's the dummy TOTP link for example:
otpauth://hotp/lunzima@jinke.la:d0210cc8-85ae-4caf-843f-68e844712365?digits=6&secret=DWC6ZZPX6IXMEPSNM2JPK54EFKWQVGZ3R4MPVUGVB5YCA7GWDUIDZMSP&counter=0&algorithm=SHA1&issuer=lunzima%40jinke.la

I tried both current WebUSB panel and old version.

**Comment by dangfan** [comment]
Please try https://canokey-console-ng.netlify.app/ instead.
