### ISSUE TITLE
offical support of esp32-s3

### ISSUE THREAD

**Issue by ghost** [canokeys/canokey-core#110]
there is a old port but it's not following the main branch

https://github.com/jocover/esp32_u2f
https://github.com/ZenithalHourlyRate/canokey-esp32

**Comment by dangfan** [comment]
Thank you for your interest in ESP32-S3 support. Currently, we do not have plans to officially support ESP32-S3. We appreciate you bringing this to our attention and understand the value this could bring. Feel free to explore the community implementations you've mentioned for your needs.
