### ISSUE TITLE
FIDO2 attestation

### ISSUE THREAD

**Issue by Idriel** [canokeys/canokey-core#112]
Hi,

Will canokey become FIDO2 attested so it can be used in Azure?
[Azure FIDO2 Vendors](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-hardware-vendor)

I think OpenSK is similar project (FIDO2 only) and it's using same HW chip and it's attested.

**Comment by dangfan** [comment]
Regrettably, the certification fees amount to at least US$9,000. We currently lack a plan to implement this.
