### ISSUE TITLE
Implement metadata for PIV applet

### ISSUE THREAD

**Issue by mochaaP** [canokeys/canokey-core#41]
See <https://github.com/canokeys/canokey-pigeon/discussions/8#discussioncomment-1932901>

**Comment by dangfan** [comment]
Unfortunately, after investigating `piv-go`, it does not use the metadata information specified by Yubico.

**Comment by mochaaP** [comment]
@dangfan 我剛檢查了一下 master branch，還在用。
https://github.com/go-piv/piv-go/blob/master/piv/piv.go#L791

**Comment by dangfan** [comment]
但这与 Yubico 定义的命令（https://docs.yubico.com/yesdk/users-manual/application-piv/apdu/metadata.html）不一致，即 https://github.com/canokeys/canokey-pigeon/discussions/8#discussioncomment-1932901 所标明的 F7 命令。

**Comment by mochaaP** [comment]
![image](https://user-images.githubusercontent.com/21154023/199175091-87c403e2-21a5-4b09-94bf-4cb3863b84f0.png)
https://docs.yubico.com/yesdk/users-manual/application-piv/commands.html#table-4b-piv-get-data-elements-empty-upon-manufacture
其實倒不是命令的問題，就是缺了個 element

**Comment by dangfan** [comment]
根据NIST的spec，RPINTED不是必须有的；另外根据Yubico的文档，这个地方的数据也不该由用户操作：

> You should never overwrite the information in the Printed tag. If you do, it could make your YubiKey unusable.

缺这个数据对使用有什么影响吗？

**Comment by mochaaP** [comment]
![image](https://user-images.githubusercontent.com/21154023/199176205-502fdec7-0bb3-43ff-a850-ecfbd5610017.png)
如圖。

**Comment by mochaaP** [comment]
![image](https://user-images.githubusercontent.com/21154023/199176611-4ee1c781-3897-4c80-9097-e8655ce50be4.png)
這個並非通用的實作，但這樣才能設定不同 touch policy.

**Comment by dangfan** [comment]
谢谢反馈

**Comment by z4yx** [comment]
最新代码已实现matadata接口和printed info，问题解决
