### ISSUE TITLE
linux 下的普通用户，确认是可以使用这个设备的吗？

### ISSUE THREAD

**Issue by atzlinux** [canokeys/canokey-core#94]
按文档进行了相关配置，
在系统上增加了 /etc/udev/rules.d/69-canokeys.rules 文件。

目前就 用 root 用户运行 gpg --card-status  能够获取卡的状态，普通用户运行报错：

gpg --card-status 
gpg: 从 ‘scdaemon’ 获取版本时出现错误: Not supported
gpg: OpenPGP 卡不可用：Not supported

OS:
Debian 12.6 

uname -a
Linux atzlinux-ce 6.9.8-rt-amd64 #1 SMP PREEMPT_RT Debian 6.9.8-1 (2024-07-07) x86_64 GNU/Linux

**Comment by raven15** [comment]
gpg会独占。你先别用管理员执行 card-status ，重启后直接用普通用户，或者把管理员那个用户的gpg相关进程先 kill 掉。我用起来发现gpg有点坑的是，会独占，有一个 gpg 进程占用后其他进程都用不了。在 windows，现在的解决办法是用git内置的gpg，不用gpg4win，ssh也是用git内置的。linux下我暂时都是一个用户用，没有遇到你的这种情况。
